
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi2.usac.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int lte = 8;
  public static final int number = 16;
  public static final int bracket_o = 12;
  public static final int minus = 3;
  public static final int mult = 4;
  public static final int lt = 6;
  public static final int gte = 9;
  public static final int bracket_c = 13;
  public static final int semicolon = 19;
  public static final int println = 21;
  public static final int div = 5;
  public static final int EOF = 0;
  public static final int par_o = 14;
  public static final int gt = 7;
  public static final int id = 17;
  public static final int error = 1;
  public static final int asign = 20;
  public static final int plus = 2;
  public static final int neq = 11;
  public static final int par_c = 15;
  public static final int var = 18;
  public static final int eq = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "plus",
  "minus",
  "mult",
  "div",
  "lt",
  "gt",
  "lte",
  "gte",
  "eq",
  "neq",
  "bracket_o",
  "bracket_c",
  "par_o",
  "par_c",
  "number",
  "id",
  "var",
  "semicolon",
  "asign",
  "println"
  };
}

